### ISSUE TITLE
Update version in README

### ISSUE THREAD

**Issue by sheerlox** [talent-ideal/semantic-release-hex#20]
### Discussed in https://github.com/talent-ideal/semantic-release-hex/discussions/17

<sup>Originally posted by **sheerlox** November 20, 2023</sup>

# Description

As proposed by @Eiji7 in [its response to the Elixir Forum announcement](https://elixirforum.com/t/semanticreleasehex-fully-automated-version-management-and-release-processes/59837/2), automatically updating the version number in the project's README during release is a must, because projects need to specify the dependency tuple to add to `mix.exs` in their "Installation" section.

# Feature specification

**Step:** `prepare`

## Requirements

- Support the various dependencies specification format (regular / git tag)
- Support the various version requirements operators

## Behavior

- Does not update complex version requirements (`and` or `or`)
- Replaces `MAJOR.MINOR` with `MAJOR.MINOR.PATCH`

### Depends on

- Ability to parse the project's app field from `mix.exs`

# Resources

## Elixir atoms format

Source: [`hexdocs.pm/elixir/Atom`](https://hexdocs.pm/elixir/1.13.4/Atom.html)

> Atoms must be composed of Unicode characters such as letters, numbers, underscore, and @.

The doc also mentions:

> If the keyword has a character that does not belong to the category above, such as spaces, you can wrap it in quotes:
> ```
> :"this is an atom with spaces"
> :"this is an atom with spaces"
> ```

But I don't think this is relevant, as this is probably not good practice, at least in a library's name.

## Mix deps format

Source: [`hexdocs.pm/mix/Mix.Tasks.Deps`](https://hexdocs.pm/mix/1.12.3/Mix.Tasks.Deps.html)

> Dependencies must be specified in the mix.exs file in one of the following formats:

```
{app, requirement}
{app, opts}
{app, requirement, opts}
```

> Where:
> - app is an atom
> - requirement is a [Version](https://hexdocs.pm/elixir/1.12/Version.html) requirement or a regular expression
> - opts is a keyword list of options

## Version Requirements

Source: [`hexdocs.pm/elixir/Version`](https://hexdocs.pm/elixir/1.12/Version.html#module-requirements)

> Requirements allow you to specify which versions of a given dependency you are willing to work against. Requirements support the common comparison operators such as `>`, `>=`, `<`, `<=`, `==`, `!=` that work as one would expect, and additionally the special operator `~>` described in detail further below.

> Requirements also support `and` and `or` for complex conditions.

> The requirement operand after the ~> is allowed to omit the patch version, allowing us to express ~> 2.1 or ~> 2.1-dev, something that wouldn't be allowed when using the common comparison operators.

## Example READMEs

- https://github.com/michalmuskala/jason#readme
- https://github.com/elixir-gettext/gettext#readme

**Comment by Eiji7** [comment]
While `Installation` is auto-generated part of `README` and therefore the most common I think that there may be more things to cover, for example usage within `Elixir`'s script file:
```elixir
# normal call
Mix.install([:my_lib])

# without optional parentheses
Mix.install [:my_lib]

# using a sigil
Mix.install ~w[my_lib]a
```
By default `mix` takes the `latest` version, but it's also possible to select specific one …
```elixir
# tuple notation
Mix.install [{my_lib, "~> 1.0"}]

# shorter keyword notation
Mix.install my_lib: "~> 1.0"
```
**Note**: In `Elixir` a `Keyword` notation is allowed at the end of `List`, as a last function/macro call argument or as a nth argument as long as it's wrapped in square brackets.

For more information please take a look at [Mix.install/2](https://hexdocs.pm/mix/Mix.html#install/2) documentation.

**Comment by sheerlox** [comment]
Let's track this here: https://github.com/talent-ideal/semantic-release-hex/discussions/21

**Comment by sheerlox** [comment]
[`chore(release): v1.0.6` on `semantic-release-hex-demo`](https://github.com/sheerlox/semantic-release-hex-demo/commit/d1e378ada976e8f24b755777b263d35c0cd3bdb9#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5) :tada:
